apiVersion: v1
kind: ReplicationController
metadata:
  name: hue
  labels:
    app: hue
    version: 1.0.0
spec:
  replicas: 1
  selector:
    name: hue
  template:
    metadata:
      labels:
        name: hue
    spec:
      containers:
      - name: hue
        image: gcr.io/synapse-157713/hue
        imagePullPolicy: "Always"
        env:
        - name: GET_HOSTS_FROM
          value: DNS
        ports:
        - containerPort: 8888
      nodeSelector:
        training: "true"
