version: '2'
services:
  nifi-seed:
    container_name: nifi-cluster-seed
    build: ./nifi
    image: nifi-example
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8443:8443"
      - "2882:2882"
    depends_on:
      - zoo1

  zoo1:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"