version: '2'
services:
  zookeeper:
    container_name: zookeeper
    hostname: zookeeper
    image: fluxcapacitor/zookeeper
    ports:
     - "2181:2181"
    networks:
     vpcbr:
       ipv4_address: 10.5.0.2

  hdfs:
    image: gcr.io/synapse-157713/hdfs
    ports:
      - "50070:50070"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.3

  hbase-master-1:
   container_name: hbase-master-1
   hostname: hbase-master-1
   image: gcr.io/synapse-157713/hbase
   environment:
     - HBASE_SERVER_TYPE=master
     - HBASE_MASTER_PORT=60000
     - HBASE_MASTER_INFO_PORT=60001
     - HBASE_REGION_PORT=60010
     - HBASE_REGION_INFO_PORT=60011
     - HDFS_SERVICE=hdfs
     - HDFS_PORT=9000
     - ZOOKEEPER_SERVICE_LIST=zookeeper
     - ZOOKEEPER_PORT=2181
     - ZNODE_PARENT=hbase
     - HBASE_MASTER_LIST=10.5.0.5:hbase-master-2
     - HBASE_REGION_LIST=10.5.0.6:hbase-region-1 10.5.0.7:hbase-region-2
   ports:
     - "60000:60000"
     - "60001:60001"
     - "9090:9090"
   links:
     - zookeeper
   networks:
     vpcbr:
       ipv4_address: 10.5.0.4

  hbase-master-2:
   container_name: hbase-master-2
   hostname: hbase-master-2
   image: gcr.io/synapse-157713/hbase
   environment:
     - HBASE_SERVER_TYPE=master
     - HBASE_MASTER_PORT=60000
     - HBASE_MASTER_INFO_PORT=60001
     - HBASE_REGION_PORT=60010
     - HBASE_REGION_INFO_PORT=60011
     - HDFS_SERVICE=hdfs
     - HDFS_PORT=9000
     - ZOOKEEPER_SERVICE_LIST=zookeeper
     - ZOOKEEPER_PORT=2181
     - ZNODE_PARENT=hbase
     - HBASE_MASTER_LIST=10.5.0.4:hbase-master-1
     - HBASE_REGION_LIST=10.5.0.6:hbase-region-1 10.5.0.7:hbase-region-2
   ports:
     - "60002:60000"
     - "60003:60001"
     - "9091:9090"
   links:
     - zookeeper
   networks:
     vpcbr:
       ipv4_address: 10.5.0.5

  hbase-region-1:
   container_name: hbase-region-1
   hostname: hbase-region-1
   image: gcr.io/synapse-157713/hbase
   environment:
     - HBASE_SERVER_TYPE=regionserver
     - HBASE_MASTER_PORT=60000
     - HBASE_MASTER_INFO_PORT=60001
     - HBASE_REGION_PORT=60010
     - HBASE_REGION_INFO_PORT=60011
     - HDFS_SERVICE=hdfs
     - HDFS_PORT=9000
     - ZOOKEEPER_SERVICE_LIST=zookeeper
     - ZOOKEEPER_PORT=2181
     - ZNODE_PARENT=hbase
     - HBASE_MASTER_LIST=10.5.0.4:hbase-master-1 10.5.0.5:hbase-master-2
     - HBASE_REGION_LIST=10.5.0.7:hbase-region-2
   ports:
     - "60004:60010"
     - "60005:60011"
     - "9092:9090"
   links:
     - zookeeper
   networks:
     vpcbr:
       ipv4_address: 10.5.0.6

  hbase-region-2:
   container_name: hbase-region-2
   hostname: hbase-region-2
   image: gcr.io/synapse-157713/hbase
   environment:
     - HBASE_SERVER_TYPE=regionserver
     - HBASE_MASTER_PORT=60000
     - HBASE_MASTER_INFO_PORT=60001
     - HBASE_REGION_PORT=60010
     - HBASE_REGION_INFO_PORT=60011
     - HDFS_SERVICE=hdfs
     - HDFS_PORT=9000
     - ZOOKEEPER_SERVICE_LIST=zookeeper
     - ZOOKEEPER_PORT=2181
     - ZNODE_PARENT=hbase
     - HBASE_MASTER_LIST=10.5.0.4:hbase-master-1 10.5.0.5:hbase-master-2
     - HBASE_REGION_LIST=10.5.0.6:hbase-region-1
   ports:
     - "60006:60010"
     - "60007:60011"
     - "9093:9090"
   links:
     - zookeeper
   networks:
     vpcbr:
       ipv4_address: 10.5.0.7

  hue:
    image: gcr.io/synapse-157713/hue
    ports:
      - "8887:8888"
    links:
      - hdfs
      - hbase-master-1
    networks:
     vpcbr:
       ipv4_address: 10.5.0.8

networks:
 vpcbr:
   driver: bridge
   ipam:
    config:
      - subnet: 10.5.0.0/16
        gateway: 10.5.0.1
