kind: Service
apiVersion: v1
metadata:
  name: nifi-http
spec:
  type: NodePort
  selector:
    app: nifi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: nifi
    - protocol: TCP
      port: 8443
      targetPort: 8443
      name: nifi-ssl

---

kind: Service
apiVersion: v1
metadata:
  name: nifi
spec:
  clusterIP: None
  selector:
    app: nifi
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      name: nifi-listen-http
    - protocol: TCP
      port: 2881
      targetPort: 2881
      name: nifi-site-protocol
    - protocol: TCP
      port: 2882
      targetPort: 2882
      name: nifi-node-protocol
